### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-html-multiple-pages-T_njfg#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://mi-449-ss17-741-html-multiple-pages-t_njfg-amanuel1995.surge.sh/) and meets the following criteria:

- [x] None of the routes on the website end with `.html`
- [x] A homepage exists, where the purpose of the site is explained
- [x] A "list page" exists that lists your top 3 favorite of this thing (e.g. `/pokemon`) -- each list item should link to the corresponding page for that favorite, detailed below
- [x] For each of your favorites, a page exists to display more information about it (e.g. `/pokemon/bulbasaur`)
- [x] Every page includes links to the homepage and list page (although pages do not have to link to themselves)

**Comment by stuartpearman** [comment]
Hey Amanuel,

Katie's a little busy so I'm picking your code review up for her.

Good content, and overall nice work. I would change just one thing to make it extra nice 👌

Read criteria 4 once more:

> For each of your favorites, a page exists to display more information about it (e.g. /pokemon/bulbasaur)

Instead of `/list/` I would change your route to be something a bit more descriptive, like in the `/pokemon/bulbasaur/` example.

And make sure to also update your links when you make changes! 🔗 😎

**Comment by amanuel1995** [comment]
Thank you for helping her out, I was wondering why I didn't see a comment in few hours. 

I think I fixed what you pointed out now. Let me know if you want more modifications.

**Comment by KatieMFritz** [comment]
@amanuel1995 , this is great! :shipit: 

@stuartpearman, thanks for helping out.

**Comment by amanuel1995** [comment]
Thanks @KatieMFritz!
